version: '3.9'

services:

  postgres:
    image: postgres:14.13-alpine3.19
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: gophkeeper
      POSTGRES_USER: gophkeeper
      POSTGRES_PASSWORD: pass
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .pginit:/docker-entrypoint-initdb.d # scripts for init db first run (sql, runs by filename a < b)
      - .pgdata:/var/lib/postgresql/data
    ports:
      - "9998:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"

#volumes:
#  pgdata:

# https://habr.com/ru/articles/578744/
